In [1]:
# Ashwin R

import pandas as pd 
import matplotlib.pyplot as plt

from sklearn import tree
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('melb_data.csv')
print(data)

              Suburb           Address  Rooms Type      Price Method  \
0         Abbotsford      85 Turner St      2    h  1480000.0      S
1         Abbotsford   25 Bloomburg St      2    h  1035000.0      S
2         Abbotsford      5 Charles St      3    h  1465000.0     SP
3         Abbotsford  40 Federation La      3    h   850000.0     PI
4         Abbotsford       55a Park St      4    h  1600000.0     VB
...              ...               ...    ...  ...        ...    ...
13575  Wheelers Hill      12 Strada Cr      4    h  1245000.0      S
13576   Williamstown     77 Merrett Dr      3    h  1031000.0     SP
13577   Williamstown       83 Power St      3    h  1170000.0      S
13578   Williamstown      96 Verdon St      4    h  2500000.0     PI
13579     Yarraville        6 Agnes St      4    h  1285000.0     SP

        SellerG        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  \
0        Biggin   3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0
1        Biggin   4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0
2        Biggin   4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0
3        Biggin   4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0
4        Nelson   4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0
...         ...         ...       ...       ...  ...       ...  ...       ...
13575     Barry  26/08/2017      16.7    3150.0  ...       2.0  2.0     652.0
13576  Williams  26/08/2017       6.8    3016.0  ...       2.0  2.0     333.0
13577     Raine  26/08/2017       6.8    3016.0  ...       2.0  4.0     436.0
13578   Sweeney  26/08/2017       6.8    3016.0  ...       1.0  5.0     866.0
13579   Village  26/08/2017       6.3    3013.0  ...       1.0  1.0     362.0

       BuildingArea  YearBuilt  CouncilArea Lattitude  Longtitude  \
0               NaN        NaN        Yarra -37.79960   144.99840
1              79.0     1900.0        Yarra -37.80790   144.99340
2             150.0     1900.0        Yarra -37.80930   144.99440
3               NaN        NaN        Yarra -37.79690   144.99690
4             142.0     2014.0        Yarra -37.80720   144.99410
...             ...        ...          ...       ...         ...
13575           NaN     1981.0          NaN -37.90562   145.16761
13576         133.0     1995.0          NaN -37.85927   144.87904
13577           NaN     1997.0          NaN -37.85274   144.88738
13578         157.0     1920.0          NaN -37.85908   144.89299
13579         112.0     1920.0          NaN -37.81188   144.88449

                       Regionname Propertycount
0           Northern Metropolitan        4019.0
1           Northern Metropolitan        4019.0
2           Northern Metropolitan        4019.0
3           Northern Metropolitan        4019.0
4           Northern Metropolitan        4019.0
...                           ...           ...
13575  South-Eastern Metropolitan        7392.0
13576        Western Metropolitan        6380.0
13577        Western Metropolitan        6380.0
13578        Western Metropolitan        6380.0
13579        Western Metropolitan        6543.0

[13580 rows x 21 columns]

In [3]:
print(data.isnull())
print(data.dtypes)
print(data.columns)
data.drop(data['Rooms'])

       Suburb  Address  Rooms   Type  Price  Method  SellerG   Date  Distance  \
0       False    False  False  False  False   False    False  False     False
1       False    False  False  False  False   False    False  False     False
2       False    False  False  False  False   False    False  False     False
3       False    False  False  False  False   False    False  False     False
4       False    False  False  False  False   False    False  False     False
...       ...      ...    ...    ...    ...     ...      ...    ...       ...
13575   False    False  False  False  False   False    False  False     False
13576   False    False  False  False  False   False    False  False     False
13577   False    False  False  False  False   False    False  False     False
13578   False    False  False  False  False   False    False  False     False
13579   False    False  False  False  False   False    False  False     False

       Postcode  ...  Bathroom    Car  Landsize  BuildingArea  YearBuilt  \
0         False  ...     False  False     False          True       True
1         False  ...     False  False     False         False      False
2         False  ...     False  False     False         False      False
3         False  ...     False  False     False          True       True
4         False  ...     False  False     False         False      False
...         ...  ...       ...    ...       ...           ...        ...
13575     False  ...     False  False     False          True      False
13576     False  ...     False  False     False         False      False
13577     False  ...     False  False     False          True      False
13578     False  ...     False  False     False         False      False
13579     False  ...     False  False     False         False      False

       CouncilArea  Lattitude  Longtitude  Regionname  Propertycount
0            False      False       False       False          False
1            False      False       False       False          False
2            False      False       False       False          False
3            False      False       False       False          False
4            False      False       False       False          False
...            ...        ...         ...         ...            ...
13575         True      False       False       False          False
13576         True      False       False       False          False
13577         True      False       False       False          False
13578         True      False       False       False          False
13579         True      False       False       False          False

[13580 rows x 21 columns]
Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object
Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
9,Abbotsford,10 Valiant St,2,h,1097000.0,S,Biggin,8/10/2016,2.5,3067.0,...,1.0,2.0,220.0,75.0,1900.0,Yarra,-37.80100,144.99890,Northern Metropolitan,4019.0
11,Abbotsford,40 Nicholson St,3,h,1350000.0,VB,Nelson,12/11/2016,2.5,3067.0,...,2.0,2.0,214.0,190.0,2005.0,Yarra,-37.80850,144.99640,Northern Metropolitan,4019.0
12,Abbotsford,123/56 Nicholson St,2,u,750000.0,S,Biggin,12/11/2016,2.5,3067.0,...,2.0,1.0,0.0,94.0,2009.0,Yarra,-37.80780,144.99650,Northern Metropolitan,4019.0
13,Abbotsford,45 William St,2,h,1172500.0,S,Biggin,13/08/2016,2.5,3067.0,...,1.0,1.0,195.0,NaN,NaN,Yarra,-37.80840,144.99730,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [4]:
df = data[['Rooms','Distance','Postcode','Bedroom2','Bathroom','Car','Landsize','BuildingArea','YearBuilt','Price']]
print(df.isnull())
df = df.dropna()
print(df.isnull())
df1 = df.reset_index(drop=True)
print(df1)

       Rooms  Distance  Postcode  Bedroom2  Bathroom    Car  Landsize  \
0      False     False     False     False     False  False     False
1      False     False     False     False     False  False     False
2      False     False     False     False     False  False     False
3      False     False     False     False     False  False     False
4      False     False     False     False     False  False     False
...      ...       ...       ...       ...       ...    ...       ...
13575  False     False     False     False     False  False     False
13576  False     False     False     False     False  False     False
13577  False     False     False     False     False  False     False
13578  False     False     False     False     False  False     False
13579  False     False     False     False     False  False     False

       BuildingArea  YearBuilt  Price
0              True       True  False
1             False      False  False
2             False      False  False
3              True       True  False
4             False      False  False
...             ...        ...    ...
13575          True      False  False
13576         False      False  False
13577          True      False  False
13578         False      False  False
13579         False      False  False

[13580 rows x 10 columns]
       Rooms  Distance  Postcode  Bedroom2  Bathroom    Car  Landsize  \
1      False     False     False     False     False  False     False
2      False     False     False     False     False  False     False
4      False     False     False     False     False  False     False
6      False     False     False     False     False  False     False
7      False     False     False     False     False  False     False
...      ...       ...       ...       ...       ...    ...       ...
13572  False     False     False     False     False  False     False
13573  False     False     False     False     False  False     False
13576  False     False     False     False     False  False     False
13578  False     False     False     False     False  False     False
13579  False     False     False     False     False  False     False

       BuildingArea  YearBuilt  Price
1             False      False  False
2             False      False  False
4             False      False  False
6             False      False  False
7             False      False  False
...             ...        ...    ...
13572         False      False  False
13573         False      False  False
13576         False      False  False
13578         False      False  False
13579         False      False  False

[6830 rows x 10 columns]
      Rooms  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  \
0         2       2.5    3067.0       2.0       1.0  0.0     156.0
1         3       2.5    3067.0       3.0       2.0  0.0     134.0
2         4       2.5    3067.0       3.0       1.0  2.0     120.0
3         3       2.5    3067.0       4.0       2.0  0.0     245.0
4         2       2.5    3067.0       2.0       1.0  2.0     256.0
...     ...       ...       ...       ...       ...  ...       ...
6825      2      14.5    3087.0       2.0       1.0  1.0     210.0
6826      4      14.7    3030.0       4.0       2.0  1.0     662.0
6827      3       6.8    3016.0       3.0       2.0  2.0     333.0
6828      4       6.8    3016.0       4.0       1.0  5.0     866.0
6829      4       6.3    3013.0       4.0       1.0  1.0     362.0

      BuildingArea  YearBuilt      Price
0             79.0     1900.0  1035000.0
1            150.0     1900.0  1465000.0
2            142.0     2014.0  1600000.0
3            210.0     1910.0  1876000.0
4            107.0     1890.0  1636000.0
...            ...        ...        ...
6825          79.0     2006.0   650000.0
6826         172.0     1980.0   635000.0
6827         133.0     1995.0  1031000.0
6828         157.0     1920.0  2500000.0
6829         112.0     1920.0  1285000.0

[6830 rows x 10 columns]

In [5]:
X = df1[['Rooms','Distance','Postcode','Bedroom2','Bathroom','Car','Landsize','BuildingArea','YearBuilt']]
Y = df1[['Price']]
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, shuffle=False)

In [6]:
dtr = DecisionTreeRegressor()
dtr.fit(x_train, y_train)
predictions = dtr.predict(x_test)
print(predictions)
print("R2 score ", r2_score(predictions, y_test))

[ 620000. 1000000. 1320000. ... 1460000. 1530000. 1330000.]
R2 score  0.41983747613197697